[package]
name = "ssnt"
version = "0.1.0"
authors = ["Alain Siegrist <alainsiegrist02@gmail.com>"]
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
bevy = { version = "0.19", default-features = false, features = ["bevy_asset", "bevy_scene", "bevy_pbr", "bevy_gltf", "bevy_sprite", "bevy_text", "bevy_render", "bevy_core_pipeline", "bevy_ui", "bevy_ui_render", "bevy_log", "bevy_state", "multi_threaded", "png", "hdr", "ktx2", "zstd_rust", "file_watcher", "bevy_gizmos", "bevy_gizmos_render", "tonemapping_luts", "default_font", "webgl2"] }
bevy_rapier3d = { path = "../bevy_rapier/bevy_rapier3d" }

[features]
default = ["client"]
client = ["bevy/bevy_animation", "bevy/bevy_audio", "bevy/bevy_gilrs", "bevy/bevy_winit", "bevy/x11", "bevy/vorbis"]

[dependencies]
byond = { path = "crates/byond" }
maps = { path = "crates/maps" }
networking = { path = "crates/networking" }
physics = { path = "crates/physics" }
utils = { path = "crates/utils" }
bevy = { workspace = true }
bevy_egui = "0.40"
bevy-inspector-egui = "0.37"
bevy_rapier3d = { workspace = true, features = ["simd-stable"] }
bevy_common_assets = { version = "0.17", features = ["ron"] }
bincode = "1.3"
cfg-if = "1.0.0"
futures-lite = "1.4.0"
log = "0.4.8"
glam = "0.32"
uuid = { version = "1", features = ["v4", "v5"] }
serde = { version = "*", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
reqwest =  { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
async-compat = "0.2.1"
tokio = { version = "1.21.2", features = ["time"] }
# Remove when https://github.com/bevyengine/bevy/pull/6578 is merged
smallvec = "*"
base64 = "0.22"

[patch.crates-io]
glamx = { path = "../glamx-ssnt" }
bevy = { path = "../bevy" }
bevy_a11y = { path = "../bevy/crates/bevy_a11y" }
bevy_android = { path = "../bevy/crates/bevy_android" }
bevy_animation = { path = "../bevy/crates/bevy_animation" }
bevy_anti_alias = { path = "../bevy/crates/bevy_anti_alias" }
bevy_app = { path = "../bevy/crates/bevy_app" }
bevy_asset = { path = "../bevy/crates/bevy_asset" }
bevy_audio = { path = "../bevy/crates/bevy_audio" }
bevy_camera = { path = "../bevy/crates/bevy_camera" }
bevy_camera_controller = { path = "../bevy/crates/bevy_camera_controller" }
bevy_clipboard = { path = "../bevy/crates/bevy_clipboard" }
bevy_color = { path = "../bevy/crates/bevy_color" }
bevy_core_pipeline = { path = "../bevy/crates/bevy_core_pipeline" }
bevy_derive = { path = "../bevy/crates/bevy_derive" }
bevy_dev_tools = { path = "../bevy/crates/bevy_dev_tools" }
bevy_diagnostic = { path = "../bevy/crates/bevy_diagnostic" }
bevy_dylib = { path = "../bevy/crates/bevy_dylib" }
bevy_ecs = { path = "../bevy/crates/bevy_ecs" }
bevy_encase_derive = { path = "../bevy/crates/bevy_encase_derive" }
bevy_feathers = { path = "../bevy/crates/bevy_feathers" }
bevy_gilrs = { path = "../bevy/crates/bevy_gilrs" }
bevy_gizmos = { path = "../bevy/crates/bevy_gizmos" }
bevy_gizmos_render = { path = "../bevy/crates/bevy_gizmos_render" }
bevy_gltf = { path = "../bevy/crates/bevy_gltf" }
bevy_image = { path = "../bevy/crates/bevy_image" }
bevy_input = { path = "../bevy/crates/bevy_input" }
bevy_input_focus = { path = "../bevy/crates/bevy_input_focus" }
bevy_internal = { path = "../bevy/crates/bevy_internal" }
bevy_light = { path = "../bevy/crates/bevy_light" }
bevy_log = { path = "../bevy/crates/bevy_log" }
bevy_macro_utils = { path = "../bevy/crates/bevy_macro_utils" }
bevy_material = { path = "../bevy/crates/bevy_material" }
bevy_math = { path = "../bevy/crates/bevy_math" }
bevy_mesh = { path = "../bevy/crates/bevy_mesh" }
bevy_pbr = { path = "../bevy/crates/bevy_pbr" }
bevy_picking = { path = "../bevy/crates/bevy_picking" }
bevy_platform = { path = "../bevy/crates/bevy_platform" }
bevy_post_process = { path = "../bevy/crates/bevy_post_process" }
bevy_ptr = { path = "../bevy/crates/bevy_ptr" }
bevy_reflect = { path = "../bevy/crates/bevy_reflect" }
bevy_remote = { path = "../bevy/crates/bevy_remote" }
bevy_render = { path = "../bevy/crates/bevy_render" }
bevy_scene = { path = "../bevy/crates/bevy_scene" }
bevy_shader = { path = "../bevy/crates/bevy_shader" }
bevy_solari = { path = "../bevy/crates/bevy_solari" }
bevy_sprite = { path = "../bevy/crates/bevy_sprite" }
bevy_sprite_render = { path = "../bevy/crates/bevy_sprite_render" }
bevy_state = { path = "../bevy/crates/bevy_state" }
bevy_tasks = { path = "../bevy/crates/bevy_tasks" }
bevy_text = { path = "../bevy/crates/bevy_text" }
bevy_time = { path = "../bevy/crates/bevy_time" }
bevy_transform = { path = "../bevy/crates/bevy_transform" }
bevy_ui = { path = "../bevy/crates/bevy_ui" }
bevy_ui_render = { path = "../bevy/crates/bevy_ui_render" }
bevy_ui_widgets = { path = "../bevy/crates/bevy_ui_widgets" }
bevy_utils = { path = "../bevy/crates/bevy_utils" }
bevy_window = { path = "../bevy/crates/bevy_window" }
bevy_winit = { path = "../bevy/crates/bevy_winit" }
bevy_world_serialization = { path = "../bevy/crates/bevy_world_serialization" }

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.maps]
opt-level = 1

[profile.dev.package.byond]
opt-level = 3
